# Generated by Django 4.1.1 on 2022-09-06 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BossModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('boss_full_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Boss',
                'verbose_name_plural': 'Bosses',
                'db_table': 'boss_table',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_full_name', models.CharField(db_column='emp_full_name', max_length=255)),
                ('position', models.CharField(db_column='position', max_length=255)),
                ('date_of_employment', models.DateField(db_column='date_of_employment')),
                ('wage', models.FloatField(db_column='wage')),
                ('boss_name', models.ForeignKey(db_column='boss_name', on_delete=django.db.models.deletion.CASCADE, to='online_catalogue_app.bossmodel')),
            ],
            options={
                'db_table': 'employee_table',
            },
        ),
    ]
